version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ${CODE_VOLUME}:/code
      - mbs2_data:/data
    depends_on:
      - db
    environment:
      MBS2_DB_HOST: db
      MBS2_DB_NAME: postgres
      MBS2_DATA_DIR: /data
    command: /loop.sh python3 engine/backend.py

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    command: /run_app.sh
    volumes:
      - ${CODE_VOLUME}:/code
      - mbs2_data:/data
    ports:
      - 6006:6006
    depends_on:
      - db
      - backend
    environment:
      MBS2_DB_HOST: db
      MBS2_DB_NAME: postgres
      MBS2_DELEGATED_HOST: backend
      MBS2_DATA_DIR: /data
      MBS2_ENVIRONMENT:
      
      
volumes:
  mbs2_data:
    external: false
